-- Migration 001: created_at を TIMESTAMP WITH TIME ZONE に変更
ALTER TABLE tasks
  ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE
  USING created_at AT TIME ZONE 'UTC';

ALTER TABLE tasks
  ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE tasks
  ALTER COLUMN created_at SET NOT NULL;
